In [28]:
import numpy as np

array_null = np.array((5,3))
print(array_null)

array_content = np.array([[1,3],[2,2],[7,7],[9,5],[10,11],[13,1]])
print(array_content)

array_zeros = np.zeros((5,3))
print(array_zeros)

array_ones = np.ones((3,3))
print(array_ones)

array_full = np.full((4,3),5)
print(array_full)

array_random = np.random.randn(3,3)
print(array_random)

array_eye = np.eye(3)
print(array_eye)

[5 3]
[[ 1  3]
 [ 2  2]
 [ 7  7]
 [ 9  5]
 [10 11]
 [13  1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
[[-2.90021197 -0.04991019  2.05498725]
 [ 0.8848245  -0.63560906  0.50322802]
 [-0.11032502 -1.62530709 -1.39335529]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
print(np.arange(10))
print(np.arange(3,10))
print(np.arange(3,10,2))

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7 8 9]
[3 5 7 9]


In [25]:
print(np.linspace(2,3,num=5))
print(np.linspace(2,3,num=5,endpoint=False))

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]


In [34]:
print(array_content)

print(array_content[1])
print(array_content[3:3,1])
print(array_content[1:3,:])
print(array_content[1:-1,:])

[[ 1  3]
 [ 2  2]
 [ 7  7]
 [ 9  5]
 [10 11]
 [13  1]]
[2 2]
[]
[[2 2]
 [7 7]]
[[ 2  2]
 [ 7  7]
 [ 9  5]
 [10 11]]
